This PR adds cURL to the terraform plugin
go-vela/vela-terraform pull request #176
Opened 2024-07-31 18:33 UTC by AjaySridhara

This adds the curl and further details in 
https://git.target.com/vela/feature-requests/issues/263

2024-08-13 15:43 UTC, wass3rw3rk requested changes
thanks for the PR, but can we combine with previous RUN statement please?

2024-08-13 15:44 UTC, wass3rw3rk commented on Dockerfile
> +RUN apk add --update --no-cache curl
combine with previous run statement

2024-08-13 18:26 UTC, AjaySridhara commented
@wass3rw3rk — Done, David. Appreciate the help in reviewing it.

2024-08-14 14:14 UTC, plyr4 approved these changes

2024-08-14 14:15 UTC, timhuynh94 approved these changes

2024-08-14 14:57 UTC, wass3rw3rk approved these changes

2024-08-14 14:57 UTC, merged